# encoding: UTF-8
# -- mode: ruby --
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define :haproxy do |haproxy|
 haproxy.vm.box = "bento/ubuntu-20.04"
 haproxy.vm.network :private_network, ip: "192.168.100.5"
 haproxy.vm.hostname = "haproxy"
 end

config.vm.define :backend1 do |backend1|
 backend1.vm.box = "bento/ubuntu-20.04"
 backend1.vm.network :private_network, ip: "192.168.100.6"
 backend1.vm.hostname = "backend1"
 end



config.vm.define :backend2 do |backend2|
 backend2.vm.box = "bento/ubuntu-20.04"
 backend2.vm.network :private_network, ip: "192.168.100.7"
 backend2.vm.hostname = "backend2"
 end

end
